package com.runtimeenabled.implementation

import android.content.Context
import com.runtimeenabled.api.AbstractSandboxedSdkProviderCompat
import com.runtimeenabled.api.MyReSdkService

/** Provides an [MyReSdkService] implementation when the SDK is loaded. */
class SdkProvider : AbstractSandboxedSdkProviderCompat() {
    /**
     * Returns the [MyReSdkService] implementation. Called when the SDK is loaded.
     *
     * This method signature (and the [AbstractSandboxedSdkProviderCompat] class) is generated by
     * the Privacy Sandbox API Compiler plugin as the entry point for the app/SDK communication.
     */
    override fun createMyReSdkService(context: Context): MyReSdkService = MyReSdkServiceImpl(context)
}
