package com.michaeltchuang.walletsdk.runtimeenabled.runtime.data.service

import android.content.Context
import com.michaeltchuang.walletsdk.runtimeenabled.runtime.domain.service.AbstractSandboxedSdkProviderCompat
import com.michaeltchuang.walletsdk.runtimeenabled.runtime.domain.service.WalletSdkService

/** Provides an [WalletSdkService] implementation when the SDK is loaded. */
class SdkProvider : AbstractSandboxedSdkProviderCompat() {
    /**
     * Returns the [WalletSdkService] implementation. Called when the SDK is loaded.
     *
     * This method signature (and the [AbstractSandboxedSdkProviderCompat] class) is generated by
     * the Privacy Sandbox API Compiler plugin as the entry point for the app/SDK communication.
     */
    override fun createWalletSdkService(context: Context): WalletSdkService =
        WalletSdkServiceImpl(context)
}
