name: "Android App Tests"

on:
  # no timezone support so cron runs in UTC time for now
  schedule:
    - cron: "8 15 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

#  android-unit-tests:
#    name: "Android App Unit Tests"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v4
#      - name: "Install JDK 21"
#        uses: actions/setup-java@v4
#        with:
#          distribution: "zulu"
#          java-version: "21"
#          cache: "gradle"
#      - name: "Run Unit Tests"
#        run: ./gradlew test
#      - name: "Archive App Unit Tests Report"
#        uses: actions/upload-artifact@v4
#        if: ${{ always() }}
#        with:
#          name: "app-unit-tests-results"
#          path: ./**/build/reports/**
#          overwrite: true

  android-lint:
    name: "Android App Lint Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"
      - name: "Run Lint Checks"
        run: ./gradlew lint
      - name: "Archive App Lint Test Results"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "app-lint-results"
          path: ./**/build/reports/**
          overwrite: true

#  android-compose:
#    name: "Android App Checks"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v4
#      - name: "Install JDK 21"
#        uses: actions/setup-java@v4
#        with:
#          distribution: "zulu"
#          java-version: "21"
#          cache: "gradle"
#      - name: "Run Android App Checks"
#        run: ./gradlew app:packageReleaseBundle
#      - name: "Archive Android App Check Results"
#        uses: actions/upload-artifact@v4
#        if: ${{ always() }}
#        with:
#          name: "android-app-results"
#          path: ./**/build/reports/**
#          overwrite: true
